### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by deepqc** [joindesk/Joindesk#1]
Hello Team, thank you for building this open-source PMTool. Do you have a working demo setup to check? 

Thank You

**Comment by pradeepk1905** [comment]
We currently do not have a demo environment, will try to get one if possible.

You can also try running Joindesk using docker
https://joindesk.github.io/Joindesk/#/setup

**Comment by pradeepk1905** [comment]
@deepqc 

Demo:
http://144.24.133.99/

Admin: [demo-admin@domain.com](mailto:demo-admin@domain.com)
Demo Project Manager: [demo-manager@domain.com](mailto:demo-manager@domain.com)
Demo Project User: [demo-user@domain.com](mailto:demo-user@domain.com)
password: Demo@123
