### ISSUE TITLE
First impressions

### ISSUE THREAD

**Issue by m4v** [joindesk/Joindesk#5]
Interesting tool, I like that the interface is simple and minimalist. I have some impressions I would like to share after playing a bit (I used the version deployed with the docker-compose from this repository)

- The initial project setup is a bit of a hassle, you need to create issue types, groups ... some sensible defaults would help a lot.
- I couldn't create a board, it needs a filter but the dropdown menu is always empty, even after creating some filters in the issue panel.
- The gantt chart is cumbersome to use since the view is fixed to a single month, you can't zoom out or move around.
- In the same vein, you can't adjust start or duration of an issue with the gantt chart.
- Can't set relations between issues, like an issue that depends or is blocked by another (or I couldn't find a way to do it).

That's it, in any case good job in building this tool.

**Comment by pradeepk1905** [comment]
Hi @m4v 

Will consider fixing and/or simplify the app based on your feedback.

For relations between issues, its available clicking on the link icon below summary of each issue. The type of links can also be customized in the admin area.

Thank you for your comment.
